# CastleGame/constants.py

#IA
EPSILON_SELECTION = 0.5
EPSILON_TURN = 0.5
EPSILON_SEL_MIN = 0.05
EPSILON_TURN_MIN = 0.05
EPSILON_SEL_DECAY = 0.99998
EPSILON_TURN_DECAY = 0.99998
SELECTION_LEARNING_RATE = 0.0001
TURN_LEARNING_RATE = 0.0001
SELECTION_REPLAY_DATA = 100_000
TURN_REPLAY_DATA = 100_000
BATCH_SIZE = 64
DISCOUNT_FACTOR = 0.9
COPY_DQN = 50

#BASE DEL JUEGO
WARRIOR_QUANTITY = 5
ABILITIES = [1, 2, 3, 4, "movPos", "movNeg"]

# --- Pesos de la función de recompensa ---
REWARD_WEIGHTS = {
    "damage": 1,
    "deaths": 10,
    "win": 1,       # WIN_REWARD ya se aplica dentro del bonus, este peso multiplica ese bonus
    "blocks": 1,
    "heal":2,
    "shaping_weight":10,
}
TURN_PENALTY = 2
WIN_REWARD = 100
MAX_TURNS = 80
MAX_DEATHS_PER_TEAM = 3

#CONSTANTES PARA LA POOL DE ENEMIGOS
MAX_MODELS = 50
EPISODES_RANGE_POOL = 500  #1% de TRAINING EPISODES
EPISODES_SAVE_MODEL = 2500 #5% de TRAINING EPISODES
POOL_PORCENTAGE = 0.3